### ISSUE TITLE
CI настроен по устаревшему гайду

### ISSUE THREAD

**Issue by stepancar** [amirymax/SofiAI#2]
<img width="1378" alt="Screenshot 2024-03-25 at 15 43 12" src="https://github.com/amirymax/SofiAI/assets/2854910/2f1eac12-3661-48e9-b4f7-e5da75885a0e">

В логах CI видно warning. Скорее всего вы следовали какому-то туториалу для настройки. 
В разработке ПО не стоит полностью доверять туториалам, если есть официальная документация, так как часто гайды и туториалы устаревают очень быстро

**Comment by amirymax** [comment]
обновил )
